controller_joint_names: ['', 'joint_1', 'Joint_2', 'Joint_3', 'joint_4', 'joint_5', 'joint_6', 'Joint_7', 'gear1_joint', 'claw_joint1', 'gear2_joint', 'claw_joint2', 'base_claw_joint2', 'base_claw_joint1', ]
